[workspace]
resolver = "3"
members = [
    "crates/lizhisim",
    "crates/lizhisim-core",
    "crates/lizhisim-rules",
]

[workspace.package]
description = "A Japanese (Riichi) mahjong game simulator."
version = "0.0.1"
authors = ["Apricot S."]
edition = "2024"
rust-version = "1.97"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Apricot-S/lizhisim"
keywords = ["mahjong", "riichi"]
categories = ["simulation"]

[workspace.metadata.release]
tag-prefix = ""

[workspace.dependencies]
lizhisim-core = { path = "crates/lizhisim-core", version = "0.0.1" }
lizhisim-rules = { path = "crates/lizhisim-rules", version = "0.0.1" }

thiserror = "2.0.20"
