name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: |
            **/*.md
            #target/**

  local-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Check local links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --offline --no-progress --root-dir . './**/*.md'
          fail: true
          failIfEmpty: true
